### PR TITLE
Add 'mermaidOptions' as plugin options

### PR DESCRIPTION
**Pull request by rheinardkorf**
`mermaidOptions` can now be used to specify additional mermaid
initialization options.

See README.md for an example.

### CODE REVIEW

**Comment by ChappIO** [comment]
Thanks! This is a good addition, would you mind linking to https://mermaidjs.github.io/#/mermaidAPI in the README so people know where to look for the available options?

**Comment by ChappIO** [comment]
Nevermind, looks like I an do that myself :)

**Comment by rheinardkorf** [comment]
Thanks @ChappIO for doing the merge.  Do you mind publishing it to `npm` when you're ready so that I can add it to my next project?

**Comment by ChappIO** [comment]
@rheinardkorf it has been published now

**Comment by rheinardkorf** [comment]
cheers

**Pull request merged**
